//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Ride_You_Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR()
        {
            this.RENTALs = new HashSet<RENTAL>();
            this.RE_TURN = new HashSet<RE_TURN>();
        }
        #region

        [Display(Name = "Car Number")]
        [Required(ErrorMessage = "Please enter Car number")]
        public string CARNO { get; set; }
        #endregion

        #region
        [Display(Name = "Car Make")]
        [Required(ErrorMessage = "Please enter Car Make")]
        public string CAR_MAKE { get; set; }
        #endregion

        #region
        [Display(Name = "Car Model")]
        [Required(ErrorMessage = "Please enter Car Model")]
        public string CAR_MODEL { get; set; }
        #endregion

        #region
        [Display(Name = "Car Body Type")]
        [Required(ErrorMessage = "Please enter Car Body Type")]
        public string CAR_BODYTYPE { get; set; }
        #endregion

        #region
        [Display(Name = "Kilometres Travelled")]
        [Required(ErrorMessage = "Please enter Car Kilometres Travelled")]
        public int KILOMETRESTRAVELLED { get; set; }
        #endregion

        #region
        [Display(Name = "Service Kilometres")]
        [Required(ErrorMessage = "Please enter Car Service Kilometres")]
        public int SERVICEKILOMETRES { get; set; }
        #endregion

        #region
        [Display(Name = "Car Availability")]
        [Required(ErrorMessage = "Please enter Car Availability")]
        public string AVAILABLE { get; set; }
        #endregion


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL> RENTALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_TURN> RE_TURN { get; set; }
        public virtual CARBODYTYPE CARBODYTYPE { get; set; }
        public virtual CARMAKE CARMAKE { get; set; }
    }
}
