//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Ride_You_Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DRIVER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRIVER()
        {
            this.RENTALs = new HashSet<RENTAL>();
            this.RE_TURN = new HashSet<RE_TURN>();
        }

        #region
        [Display(Name = "Driver Name")]
        [Required(ErrorMessage = "Please enter a Name")]
        public string DRIVER_NAME { get; set; }
        #endregion

        #region
        [Display(Name = "Driver Address")]
        [Required(ErrorMessage = "Please enter an address")]
        public string DRIVER_ADDRESS { get; set; }
        #endregion

        #region
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Please enter an Email address")]
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }
        #endregion

        #region
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Please enter a mobile number")]
        [DataType(DataType.PhoneNumber)]
        public int MOBILE { get; set; }
        #endregion

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL> RENTALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_TURN> RE_TURN { get; set; }
    }
}
