//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Ride_You_Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class INSPECTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSPECTOR()
        {
            this.RENTALs = new HashSet<RENTAL>();
            this.RE_TURN = new HashSet<RE_TURN>();
        }

        #region
        [Display(Name = "Inspector ID")]
        [Required(ErrorMessage = "Please enter an Inspector ID")]
        public string INSPECTORID { get; set; }
        #endregion

        #region
        [Display(Name = "Inspector Name")]
        [Required(ErrorMessage = "Please enter a Name")]
        public string INSPECTOR_NAME { get; set; }
        #endregion

        #region
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Please enter an email address")]
        [DataType(DataType.EmailAddress)]

        public string EMAIL { get; set; }
        #endregion

        #region
        [Display(Name = "Mobile Number")]
        [Required(ErrorMessage = "Please enter a mobile number")]
        [DataType(DataType.PhoneNumber)]

        public int MOBILE { get; set; }
        #endregion

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL> RENTALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_TURN> RE_TURN { get; set; }
    }
}
