//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Ride_You_Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RE_TURN
    {
        #region
        [Display(Name = "Return ID")]
        [Required(ErrorMessage = "Please enter a Return ID")]
        public string RETURNID { get; set; }
        #endregion

        #region
        [Display(Name = "Rental ID")]
        [Required(ErrorMessage = "Please enter a Rental ID")]
        public string RENTALID { get; set; }
        #endregion

        #region
        [Display(Name = "Car number")]
        [Required(ErrorMessage = "Please enter a car number")]
        public string CARNO { get; set; }
        #endregion

        #region
        [Display(Name = "Inspector Id")]
        [Required(ErrorMessage = "Please enter a Inspector ID")]
        public string INSPECTORID { get; set; }
        #endregion

        #region
        [Display(Name = "Driver Name")]
        [Required(ErrorMessage = "Please enter a Name")]
        public string DRIVER_NAME { get; set; }
        #endregion

        #region
        public System.DateTime RETURN_DATE { get; set; }

        [Display(Name = "Elapsed Date")]
        [Required(ErrorMessage = "Please enter a date")]
        [DataType(DataType.Date)]
        public int ELAPSED_DATE { get; set; }
        #endregion

        #region
        [Display(Name = "Fine")]
        [Required(ErrorMessage = "Please enter the fine amount")]
        [DataType(DataType.Currency)]
        public int FINE { get; set; }
        #endregion

        #region
        [Display(Name = "Car")]
        [Required(ErrorMessage = "Please enter a car")]
        public virtual CAR CAR { get; set; }
        #endregion

        #region
        [Display(Name = "Driver Name")]
        [Required(ErrorMessage = "Please enter a name")]
        public virtual DRIVER DRIVER { get; set; }
        #endregion

        #region
        [Display(Name = "Inspector")]
        [Required(ErrorMessage = "Please enter an inspector")]
        public virtual INSPECTOR INSPECTOR { get; set; }
        #endregion

        #region
        [Display(Name = " Rental")]
        [Required(ErrorMessage = "Please enter a rental")]
        public virtual RENTAL RENTAL { get; set; }
        #endregion
    }
}
