//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Ride_You_Rent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RENTAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENTAL()
        {
            this.RE_TURN = new HashSet<RE_TURN>();
        }

        #region
        [Display(Name = "Rental ID")]
        [Required(ErrorMessage = "Please enter a rental ID")]
        public string RENTALID { get; set; }
        #endregion

        #region
        [Display(Name = "Car Number")]
        [Required(ErrorMessage = "Please enter a car number")]
        public string CARNO { get; set; }
        #endregion

        #region
        [Display(Name = "Inspector ID")]
        [Required(ErrorMessage = "Please enter an Inspector ID")]
        public string INSPECTORID { get; set; }
        #endregion

        #region 

        [Display(Name = "Driver Name")]
        [Required(ErrorMessage = "Please enter a Name")]
        public string DRIVER_NAME { get; set; }
        #endregion

        #region
        [Display(Name = "Rental Fee")]
        [Required(ErrorMessage = "Please enter a rental fee")]
        public int RENTAL_FEE { get; set; }
        #endregion

        #region
        [Display(Name = "Start Date")]
        [Required(ErrorMessage = "Please enter a start date")]
        [DataType(DataType.Date)]

        public System.DateTime STARTDATE { get; set; }
        #endregion

        #region
        [Display(Name = "End Date")]
        [Required(ErrorMessage = "Please enter a end date")]
        [DataType(DataType.Date)]

        public System.DateTime ENDDATE { get; set; }
        #endregion

        #region
        [Display(Name = "Car")]
        [Required(ErrorMessage = "Please enter a Car")]
        public virtual CAR CAR { get; set; }
        #endregion

        #region
        [Display(Name = "Driver")]
        [Required(ErrorMessage = "Please enter a Driver")]
        public virtual DRIVER DRIVER { get; set; }
        #endregion

        #region
        [Display(Name = "Inspector")]
        [Required(ErrorMessage = "Please enter an inspector")]
        public virtual INSPECTOR INSPECTOR { get; set; }
        #endregion

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_TURN> RE_TURN { get; set; }
    }
}
